apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    owner: juacompe
    version: "1.0"
    module: web
    environment: development
spec:
  containers:
    - name: web
      image: juacompe/heroweb
      ports:
        - containerPort: 80
          protocol: TCP