apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    owner: juacompe
    version: "1.0"
    module: web
    environment: development
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
    nodePort: 31000
  selector:
    name: web
    owner: juacompe
    version: "1.0"
    module: web
    environment: development
